Part7
slydevruby/test-guru pull request #18
Opened 2024-03-02 15:57 UTC by slydevruby

Часть 7. Rails controller 
1. Ресурсы у меня пока что не shallow. Я не знаю, как доставать test_id из /question/:id
2. plain text: "error" почему-то не работает, в логе пишется, что отрисовал, но на странице ничего не меняется. Поэтому render inline

2024-03-03 10:02 UTC, VidgarVii requested changes

2024-03-03 10:02 UTC, VidgarVii commented on .byebug_history
> +c
подобные  файлы стоит указать в gitignore.  К проекту они не относятся

2024-03-03 10:02 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +class AnswersController < ApplicationController
по ТЗ пока надо сделать QuestionsController. Оставлю замечания для него, так как ошибки одни и теже

2024-03-03 10:02 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions do
для "облегчения" роутинга рекомендуется использовать (где это возможно и приемлемо) опцию `shallow: true`
Это уменьшит кол-во запросов в контроллере. Упростит код и укоротит http запрос
[вот](http://rusrails.ru/rails-routing#melkoe-vlozhenie) документация

2024-03-03 10:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  before_action :find_test
при использовании опции shallow в роутах, поиск теста не во всех экшенах нужен

2024-03-03 10:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @test.questions.find(params[:id]).destroy
поиск вопроса дублирующая операция. Значит можно вынести в колбек.
Так же чтобы найти нужный вопрос по ИД, тест для этого не нужен

2024-03-03 10:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    if @question.save
тут происходит двойная попытка сохранения вопроса в базу.
Достаточно 1 раз породить объект в памяти и попытаться его записать.

2024-03-03 10:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      #render :new, status: :unprocessable_entity
подобные комметарии надо убирать. Этот мусор не должен попадать в код

2024-03-03 10:02 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
`test_id` не нужно в разрешенных параметрах в явном виде указывать
этот параметр не передается под ключом `question`, как ты здесь указал, Посмотри лог, где приходит test_id.
И надо разобраться в созданных путях запроса

2024-03-03 10:02 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +
достаточно 1 отступа

2024-03-03 10:02 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  def index
а тут почему-то нет пустой строки.
Вообще класс написан очень грязно. Такой код вообще не должен попадать на ревью. Всегда перепроверяй себя и пользуйся линтером

2024-03-03 10:02 UTC, VidgarVii commented on app/views/answers/new.html.erb
> +<% end %>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-03-03 10:02 UTC, VidgarVii commented on app/views/answers/new.html.erb
> +<%= form_with model: [ @test, @question, @question.answers.build ] do |form| %>
для создания ответа, тест не нужен

2024-03-04 14:31 UTC, VidgarVii requested changes

2024-03-04 14:31 UTC, VidgarVii commented on app/assets/stylesheets/tests.css
> + }
No new lina at end of file

2024-03-04 14:37 UTC, VidgarVii requested changes

2024-03-04 14:37 UTC, VidgarVii commented on app/views/questions/show.html.erb
> +
для чего столько пустых строк?

2024-03-04 14:37 UTC, VidgarVii commented on app/views/users/index.html.erb
> +<% console %>
это не должно попадать в репозиторий

2024-03-04 14:37 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +
не стоит делать то чего нет по ТЗ или в скринкасте. Много придется исправлять на следующем ТЗ

2024-03-04 14:37 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    #    render plain: 'Тест не найден'
этот коммент ни какой пользы не несёт. Он не нужен в мастере

2024-03-04 14:37 UTC, slydevruby commented on app/assets/stylesheets/tests.css
> + }
Исправил

2024-03-05 14:43 UTC, VidgarVii requested changes

2024-03-05 14:43 UTC, VidgarVii commented on .erb-lint.yml
> +        Enabled: false
когда это мы начали нарушать общепринятые соглашения? рубокоп действительно надо настраивать. Но с этими отключенными копами я не согласен. Надо исправлять замечания рубокопа, а не отключать его. Файл под удаление

2024-03-05 14:43 UTC, VidgarVii commented on app/assets/stylesheets/tests.css
> +
тут скорей всего затясался пробел

2024-03-05 14:43 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @test = @question.test
инстанс переменная для теста тут не нужна. Так как мы не передаем ни какие данные во вью destroy. Да и вью такого нет

2024-03-05 14:43 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(@test)
test_path(@question.test)

2024-03-05 14:43 UTC, VidgarVii commented on app/views/answers/_answer.html.erb
> +</li>
тут надо поправить отступы

2024-03-05 14:43 UTC, VidgarVii commented on app/views/answers/index.html.erb
> +</ol>
тут надо поправить отступы

2024-03-05 14:43 UTC, VidgarVii commented on app/views/questions/_question.html.erb
> +</li>
тут надо поправить отступы

2024-03-05 14:43 UTC, VidgarVii commented on app/views/questions/_form.html.erb
> +<% end %>
тут надо поправить отступы

2024-03-05 14:43 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +</ol>
тут надо поправить отступы

2024-03-05 14:43 UTC, VidgarVii commented on app/views/questions/show.html.erb
> +</ol>
тут надо поправить отступы

2024-03-05 14:43 UTC, VidgarVii commented on app/views/tests/_form.html.erb
> +<% end %>
и т.д

2024-03-06 11:04 UTC, slydevruby commented on app/controllers/questions_controller.rb
> +    redirect_to test_path(@test)
Так не будет работать, @question после destroy будет nil 
Я сделал так:
    test = @question.test
    @question.destroy
    redirect_to test_path(test)

2024-03-06 23:58 UTC, merged