Part8
slydevruby/test-guru pull request #19
Opened 2024-03-07 07:16 UTC by slydevruby

Представление ресурсов

2024-03-07 14:41 UTC, VidgarVii requested changes

2024-03-07 14:41 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>  end
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2024-03-07 14:41 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>  end
так же и для AnswersController

2024-03-07 14:41 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    link_to 'github', "https://github.com/#{author}/#{repo}", rel: %w[nofollow noopener]
ссылки на сторонние ресурсы правильно открывать в новой вкладке

2024-03-07 14:41 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +    case action_name
Полагаться на глобальное состояние опасно. Я про action_name. Экшенов может быть больше чем CRUD, и если этот хелпер будет вызываться в других экшенах, то метод может выдать не корректный результат.
Я всё же предлагаю передавать сюда объект вопроса.
А по состоянию персистентный объекта (.persisted?` или `.new_record?) определять контекст. С входящими аргументами работать всегда безопасней, чем полагаться на текущее состояние сервера

2024-03-07 14:41 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +  <% @questions.each do |question| %>
для рендера коллекций обычно используют render collection
http://rusrails.ru/layouts-and-rendering-in-rails#rendering-kollektsiy

```ruby
  render @questions
```

- Это разгрузит данный файл
- Наведет порядок. Вся работа с нужными ресурсами будет вестись в своей папке
- Позволит удобней кешировать куски страницы

в скринкасте про лэйауты и паршелы рассказывается про рекомендуемый вариант рендеринга коллекций (примерно после 20:30)

2024-03-07 14:55 UTC, slydevruby commented on app/views/questions/index.html.erb
> +  <% @questions.each do |question| %>
Если 
```
что приводит к следующим выводам:
экшен index в классе QuestionsController лишний
```
зачем тогда этот файл и наводить в нём порядок?

2024-03-07 15:05 UTC, slydevruby commented on app/controllers/questions_controller.rb
>  end
- Контроллер tests есть давным-давно.
- Вопросы с самого начала выводились на странице теста.
- И AnswerController не было в ТЗ, поэтому я и удалил его
- Вот твое замечание к прошлому ПР

https://github.com/slydevruby/test-guru/pull/18#discussion_r1510226968

https://github.com/slydevruby/test-guru/pull/18#discussion_r1511264879

2024-03-07 15:41 UTC, slydevruby commented on app/views/questions/index.html.erb
> +  <% @questions.each do |question| %>
Рендеры коллекций у меня везде, кроме этого файла

2024-03-08 08:59 UTC, VidgarVii requested changes

2024-03-08 08:59 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  end
тут что-то аномальное. Так множественные условные операторы не используют. Есть на много проще инструмент. Просто условный оператор if

2024-03-08 08:59 UTC, VidgarVii commented on app/views/layouts/application.html.erb
>  </html>
чтобы не усложнять файл application.html.erb лучше  footer и flash вынести в отдельные паршалы

2024-03-08 08:59 UTC, VidgarVii commented on app/views/questions/index.html.erb
>  <h1>Questions#index</h1>
этот файл надо было удалить

2024-03-08 08:59 UTC, VidgarVii commented on app/controllers/users_controller.rb
>    def create
создание юзера будем проходить на уроке аутентификации. И будем делать сразу правильно. Сейчас этот контроллер и вью лучше удалить

2024-03-08 08:59 UTC, VidgarVii commented on app/views/answers/_new.html.erb
> +<%= form_with model: [ @question, @question.answers.build] do |form| %>
лишний пробел

2024-03-08 08:59 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +  <% @questions.each do |question| %>
данное замечание относилось не только к данному файлу. А этот файл надо удалить

2024-03-08 08:59 UTC, VidgarVii commented on app/views/users/index.html.erb
> +  <% @users.each do |user| %>
вот ситуация когда не используется рендер коллекций, должна быть. Но этот файл тоже надо удалить. И я это пишу не потому что файл под удаление. А потому что тема не была усвоена и код не было перепроверен.

2024-03-14 10:57 UTC, merged