Part10
slydevruby/test-guru pull request #21
Opened 2024-03-16 14:44 UTC by slydevruby

1. Добавьте в сессию идентификатор пользователя после его регистрации
2. Создайте хэлпер для flash сообщений
3. Реализуйте выход пользователя из системы
4. Создайте навигацию с названием проекта и ссылками для регистрации/логина/выхода пользователя. Если пользователь находится в системе - выводить сообщение Welcome, <user name> Guru. Название проекта должно быть ссылкой и вести на главную страницу приложения.
5. Разрешите действия над остальными ресурсами только для пользователя который вошел в систему
6. С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально
7. Проверяйте формат и уникальность атрибута email для пользователя
8. Используйте объект текущего пользователя при старте прохождения теста

2024-03-17 11:39 UTC, VidgarVii requested changes

2024-03-17 11:39 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    session[:return_to] = request.original_url
для за логиненного пользователя это делать не надо. Может привести к неожиданным багам

2024-03-17 11:39 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:return_to]
return_to может не быть. Мы не может отвечать за данные во внешней среде. Тут нужно добавть поведение по умолчанию
Так же после return_to хорошо бы сразу удалить, так как больше эта запись будет не нужна

2024-03-17 11:39 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user = current_user
в общем-то `@user` больше вообще не нужен в контроллере
правильно будет просто везде, где нужно обращаться непосредственно к `current_user`

2024-03-17 11:39 UTC, VidgarVii commented on app/helpers/sessions_helper.rb
> +    end
ключи у флеша могут быть разные, не обязательно `:alert` и `:notice`
хотелось бы чтобы возвращалось сообщение любого типа (если оно есть - и "если оно есть" - стоит проверять в хелпере)
`css` класс будет правильно вычислять (конструировать) с помощью того же пришедшего в аргументах значения `type`
так хелпер станет более универсальным и полезным

2024-03-17 11:39 UTC, VidgarVii commented on app/models/user.rb
> +  def tests_by_level(lev)
самая баз смысленная и придающий запах исправление

2024-03-17 11:39 UTC, VidgarVii commented on app/views/application/_nav.html.erb
> +    <%= link_to 'Logout', logout_path %>
будет правильно соблюдать конвенции REST: удаление ресурса (сессии) логично делать через HTTP-метод DELETE, а не через GET (в рельсах именно так и делают)

2024-03-17 11:43 UTC, slydevruby commented on app/models/user.rb
> +  def tests_by_level(lev)
👍 это рубокоп из такого 
` tests.where(levl: level)`
сделал такое
`tests.where(level: )`
а я закоммитил

2024-03-17 11:45 UTC, slydevruby commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:return_to]
Да, я про это тоже думал, что надо проверять session[:return_to]

2024-03-17 11:46 UTC, slydevruby commented on app/views/application/_nav.html.erb
> +    <%= link_to 'Logout', logout_path %>
Понял, спасибо

2024-03-17 14:00 UTC, slydevruby commented on app/helpers/sessions_helper.rb
> +    end
Если метод flash_messages будет принимать аргументы, то есть надо во всех вью писать flash_messages(:alert), потом flash_messages(:notice) и т.д., то, на мой взгляд, **универсальным** он не будет

2024-03-18 05:34 UTC, VidgarVii requested changes

2024-03-18 05:34 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +    end
1. По ТЗ надо использовать куки. Для открытых и временных данных это более чем достаточно.
2. Лучше полностью удалять запись. Ключи со значением nil плохая практика. Используй метод delete
3. все можно сделать проще
redirect_to cookies.delete(:return_to) || tests_path

2024-03-18 05:34 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +    if session[:return_to].present?
return_to слабоватое название. 
Через пару дней не вспомнишь для чего оно надо было

2024-03-18 12:20 UTC, slydevruby commented on app/controllers/sessions_controller.rb
> +    end
![cookies](https://github.com/slydevruby/test-guru/assets/157487154/5c406773-fd11-426f-95d3-3f5e744e55b1)

2024-03-18 12:32 UTC, slydevruby commented on app/controllers/sessions_controller.rb
> +    end
Да, так лучше

2024-03-18 12:42 UTC, merged