Part14 x
slydevruby/test-guru pull request #31
Opened 2024-04-03 11:29 UTC by slydevruby

2024-04-04 15:20 UTC, VidgarVii requested changes

2024-04-04 15:20 UTC, VidgarVii commented on app/controllers/passages_controller.rb
> +  def gist
Повод вспомнить про REST.
Gist это ресурс. Значит согласно rails way и REST для создания ресурса и записи в БД объекта Gist должен быть отдельный контроллер с экшеном create

2024-04-04 15:20 UTC, VidgarVii commented on app/controllers/passages_controller.rb
> +    if obj
а его может не быть?)
тут проверяется только наличие какого-то результата, а не его успешность или корректность.
result может содержать цифру 1. И при этом будет попытка записи гиста в бд

есть стандартный принятый подход для сервисов

if result.success?

2024-04-04 15:20 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +class GitHubClient
Зачем нужна эта обертка?) Она не делает ничего полезного - можно напрямую с Octokit работать. И не надо будет тестировать отдельный класс.
GistQuestionService уже является как бы адаптером над Octokit

2024-04-04 15:20 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    @client.create_gist(gist_params)
Метод call должен вернуть такой объект, который содержит все нужные методы и данные. И хорошо если всё это будет прописано в явном виде. Сейчас же не понятно от куда берутся методы такие как html_url. 
Для создания такого объекта можно воспользоваться Struct 
Минус твоего подхода в том, что если придётся менять гем, то придётся исправлять код в разных местах проекта. А класс GistQuestionService служит своего рода адаптером над октокит. Его задача не только создавать гист. Это он вообще делегирует гему октокит. А скрыть сложность создания гиста и предоставить общий интерфейс, который не зависит от хттп клиента. И если придётся менять этот хттп клиент, то рефакторигну подвергнется только сервис  GistQuestionService

2024-04-04 15:20 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2024-04-05 12:16 UTC, slydevruby commented on app/services/gist_question_service.rb
> +  end
у меня в markdown, так просто уже не получится

2024-04-05 12:17 UTC, slydevruby commented on app/services/gist_question_service.rb
> +    @client.create_gist(gist_params)
Хорошо

2024-04-05 19:41 UTC, VidgarVii requested changes

2024-04-05 19:41 UTC, VidgarVii commented on app/controllers/admin/gists_controller.rb
> +    if result
посмотри еще раз прошлое замечание. Тут ни чего не поменялось

2024-04-05 19:41 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    [result.html_url, @client.last_response.present?]
ООП подразумевает совокупность объектов. Мы думаем объектами, работаем с объектами. 
Как уже писал есть стандартный подход для контроллера при работе с любым сервисом

```ruby
result = SomeService.new(...).call

if result.success?
  ...
else
  ...
end
```
Значит метод call должен вернуть такой **объект**, который содержит все нужные методы и данные
Для создания такого объекта можно воспользоваться Struct

2024-04-05 19:41 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
что значит не получится?

2024-04-09 11:07 UTC, merged