Badges
slydevruby/test-guru pull request #50
Opened 2024-10-04 09:32 UTC by slydevruby

2024-10-04 14:53 UTC, VidgarVii requested changes

2024-10-04 14:53 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +  end
когда возвращаем только 1 тип данных, то respond_to тут лишний

2024-10-04 14:53 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +class Admin::BadgesController < Admin::BaseController
хотелось бы чтобы ты разобрался в проблеме Style/ClassAndModuleChildren

2024-10-04 14:53 UTC, VidgarVii commented on app/views/admin/badges/_badge.html.erb
> +</li>
надо везде исправить конец файла

2024-10-04 14:53 UTC, VidgarVii commented on app/views/admin/badges/_badge.html.erb
> +    <% end %>
во 1 тут надо править отступы
во 2, есть готовое решение когда нет картинки
смотри onerror.
Отлавливать ошибку вариант рабочий но медленный. Да и зачем отлавливать возможную ошибку, когда можно её избежать. И для подобного кода место в хелпере. Тогда не будем перенагружать вью.

2024-10-04 14:53 UTC, VidgarVii commented on app/models/badge.rb
> +  default_scope { order(title: :asc) }
`default_scope` глобально меняет поведение всех запросов к модели
поэтому его [рекомендуют](https://github.com/rubocop-hq/rails-style-guide#macro-style-methods) записывать в самом верху класса

2024-10-04 14:53 UTC, VidgarVii commented on app/models/badge.rb
> +  default_scope { order(title: :asc) }
вообще default_scope является плохой практикой, так как это всегда неожиданное поведение

2024-10-04 14:53 UTC, VidgarVii commented on app/models/badge.rb
> +  enum :rule, %i[category test level]
и тут строка не на своём месте
https://github.com/rubocop/rails-style-guide?tab=readme-ov-file#macro-style-methods

2024-10-04 14:53 UTC, VidgarVii commented on app/models/badge.rb
> +  has_many :users
не уверен что тут правильная связь

2024-11-24 18:47 UTC, VidgarVii requested changes

2024-11-24 18:47 UTC, VidgarVii commented on Session.vim
> +let SessionLoad = 1
данный файл к проекту не относится. Личные настройки в репощзиторий класть не стоит

2024-11-24 18:47 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +      # @badges = Badge.order(:created_at).all
отладочный код надо удалять. Ну или стоит определиться и оставить нужный код)
вызво .all тут лишний

2024-11-24 18:47 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +      respond_to do |format|
respond_to тут не нужен, так как экшен отрабатывает только 1 формат html

2024-11-24 18:47 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +      respond_to do |format|
и тут не нужен respond_to

2024-11-24 18:47 UTC, VidgarVii commented on app/controllers/admin/gists_controller.rb
> +    def create
интересно как это сюда попало. Создание гист это функциональность обычных пользователей, а не админа

2024-11-24 18:47 UTC, VidgarVii commented on app/controllers/admin/passages_controller.rb
> +    def destroy
по ТЗ мы не создавали PassagesController index и destroy

2024-11-24 18:47 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +      params.require(:test).permit(:title, :level, :timeout, :category_id, :author_id)
author_id тут не нужен. Автор определяется в самом экшене

2024-11-24 18:47 UTC, VidgarVii commented on app/helpers/admin/categories_helper.rb
> +    def category_helper(title)
по названию метода ни когда не догадаешься, что он возвращает какое-то число. Да и судя по коду, не место ему в хелпере.

2024-11-24 18:47 UTC, VidgarVii commented on app/helpers/badges_helper.rb
> +      Test.order(:level).select(:level).distinct.all.pluck(:level).index(parameter)
вызов all тут не нужен

2024-11-24 18:47 UTC, VidgarVii commented on app/helpers/badges_helper.rb
> +module BadgesHelper
хелперы нужны для упрощение верстки. В идеале эти методы должны возвращать html код. Тут же всё не так. Подобный код надо оставлять либо в модели либо в сервисах

2024-11-24 18:47 UTC, VidgarVii commented on app/controllers/passages_controller.rb
> +      @passage.give_award(current_user) if @passage.grade > Passage::PASSAGE_MAX
можно было бы создать правило типа - Завалить тест 5 раз подряд. 
А данная проверка не позоляет это сделать

2024-11-24 18:47 UTC, VidgarVii commented on app/models/passage.rb
> +    Badge.all.each do |badge|
лучше используй find_each для итераций.
метод .all почти не используют. Так как если в БД окажется большое кол-во данных, то данный метод полностью заполнит оперативную память.  И сервер зависнет

2024-11-24 18:47 UTC, VidgarVii commented on app/models/passage.rb
>    def assign_first_question
На лицо божественный объект с нарушением закона Деметры.
с такими методами модель перестаёт быть моделью.
Модель нам помигает работать с таблицами в базе. И модель отвечает только за работу со своими данными в таблицы. Изучи паттерн ActiveRecord. А тут сейчас происходят целые бизнес процессы по выдачи баджей. Коду по выдаче баджей и правил тут не место

2024-11-24 18:47 UTC, VidgarVii commented on app/views/admin/badges/_badge.html.erb
> +    <%= Category.find(badge.parameter).title %>
так нельзя делать. При итерации баджей каждый раз будет отправляться запрос в БД. Такое надо оптимизировать.

2024-11-26 13:10 UTC, slydevruby commented on app/helpers/badges_helper.rb
> +module BadgesHelper
Так этот код и используется только теге в html. Какой смысл его в модели? Сервис разве не про расширение функционала модели за пределами БД?

2024-11-26 13:10 UTC, slydevruby commented on app/controllers/passages_controller.rb
> +      @passage.give_award(current_user) if @passage.grade > Passage::PASSAGE_MAX
Так этого не было в ТЗ, там все про прохождение, но не заваливание.

2024-11-26 13:12 UTC, slydevruby commented on app/models/passage.rb
> +    Badge.all.each do |badge|
Я это знаю, и именно потому что таблица маленькая, использовал all. 
Поправлю

2024-11-26 15:49 UTC, VidgarVii requested changes

2024-11-26 15:49 UTC, VidgarVii commented on db/migrate/20241123084829_add_timeout_to_tests.rb
> +    add_column :tests, :timeout, :integer, default: 0
этот код относится к другому тз. От сюда надо его убрать

2024-11-26 15:49 UTC, VidgarVii commented on app/controllers/admin/base_controller.rb
> +class Admin
вообще очень грубая ошибка класс использоваться как namespace
Тут должен быть модуль

2024-11-26 15:49 UTC, VidgarVii commented on app/helpers/badges_helper.rb
> +module BadgesHelper
БД он всегда за пределами. Сервисы нужны не для расширения функционала моделей. Модель это просто сущность, которая нужна для выполнения бизнес задачи. Сама по себе модель в идиале ни чего не должна делать для бизнеса. А вот сервисы как раз используют для совершения бизнес процессов. 
Бадж - сущность, которую можно описать в модели.
ВыдачаНаграды - сервис который инкапсулирует в себе бизнес логику для выдачи баджей.
Часто используют группу сервисов для выполнения какой-то задачи. Это надо для более лучшей декомпозиции задач. Текущее ТЗ как раз тот случай 

А сейчас вся логику размазана по всему рейлс приложению.

2024-11-26 15:49 UTC, VidgarVii commented on app/javascript/controllers/hello_controller.js
>  import { Controller } from "@hotwired/stimulus"
этот HelloController зачем нужен?

2024-11-26 15:50 UTC, VidgarVii commented on app/models/passage.rb
> +    Badge.all.each do |badge|
это она сейчас маленькая. Метод all почти ни когда не используется. А если и есть, то первый звонок, что код надо рефакторить

2024-11-26 15:53 UTC, VidgarVii commented on app/controllers/passages_controller.rb
> +      @passage.give_award(current_user) if @passage.grade > Passage::PASSAGE_MAX
В ТЗ вообще не было этой проверки. 
И все правила даны ради примера. Правил может быть сколько угодно. По этому в ТЗ указано, что админ может сам создавать баджы на основе текущих правил и задавать парметров. Надо учесть что правил может быть сколько угодно без раздутия классов, размазывания кода по проекту и чтобы удобно этот код можно было читать и создавать новые правила, добавляя 1 — 2 класса

2024-11-27 13:59 UTC, slydevruby commented on app/controllers/admin/base_controller.rb
> +class Admin
![Screenshot 2024-11-27 205916](https://github.com/user-attachments/assets/82736f4c-dfca-4d92-991e-0019a271624b)

2024-11-27 14:07 UTC, slydevruby commented on app/helpers/badges_helper.rb
> +module BadgesHelper
"Модель это просто сущность, которая нужна для выполнения бизнес задачи. Сама по себе модель в идиале ни чего не должна делать для бизнеса. "
???

2024-11-27 14:09 UTC, slydevruby commented on app/controllers/passages_controller.rb
> +      @passage.give_award(current_user) if @passage.grade > Passage::PASSAGE_MAX
В прошлых ТЗ было принято считать тест пройденным при оценке больше 85%.

2024-11-29 16:24 UTC, VidgarVii commented on app/controllers/admin/base_controller.rb
> +class Admin
всё правильно. У тебя есть класс Admin и ты пытаешь создать модуль Admin. От сюда появляются конфликты в названиях. Эту проблему надо решить, а не использовать класс в роли неймспейса

2024-11-29 16:25 UTC, VidgarVii commented on app/javascript/controllers/hello_controller.js
>  import { Controller } from "@hotwired/stimulus"
два выше замечания не были исправлены

2024-11-29 16:27 UTC, VidgarVii requested changes

2024-11-29 16:27 UTC, VidgarVii commented on db/migrate/20241123084829_add_timeout_to_tests.rb
> +    add_column :tests, :timeout, :integer, default: 0
не убран

2024-11-29 16:27 UTC, VidgarVii commented on app/controllers/admin/passages_controller.rb
> +  class PassagesController < Admin::BaseController
для чего нужен пустой контроллер?

2024-11-29 16:27 UTC, VidgarVii commented on app/controllers/passages_controller.rb
> +      Award.give(current_user, @passage.test) if @passage.grade > Passage::PASSAGE_MAX
я уже писал про то что логику правил выдавать бадж или нет стоит абстрагировать в 1 место

2024-11-29 16:27 UTC, VidgarVii commented on app/helpers/badges_helper.rb
> +module BadgesHelper
да. Что тут не так?

2024-11-29 16:36 UTC, slydevruby commented on app/helpers/badges_helper.rb
> +module BadgesHelper
Тут противоречие: "модель ..нужна для .. бизнес-задачи. Модель ничего не должна для бизнеса"
Что-то одно должно быть.

2024-12-09 06:46 UTC, VidgarVii commented on app/controllers/admin1/answers_controller.rb
> +module Admin1
какое-то очень странное название для админки.

2024-12-09 06:46 UTC, VidgarVii commented on app/models/passage.rb
> +    self.grade = 100 * correct_questions / test.questions.count
лучше, чтоб при делении одно число было нецелым (`float`)
сейчас у тебя результат - `integer`, т.е. происходит округление до целого по умолчанию
сравни:
```
2.6.0 :001 > 3/2
 => 1
2.6.0 :002 > 3.0/2
 => 1.5
2.6.0 :003 >
```

2024-12-10 10:59 UTC, merged